services:
  immich-redis:
    image: docker.io/valkey/valkey:${REDIS_VERSION}
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100 #Mandatory for Synology NAS
    environment:
      TZ: ${TZ}
    volumes:
      - ${REDIS_LOCATION}:/data:rw
    restart: unless-stopped

  immich-db:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:rw
    environment:
      TZ: ${TZ}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: ${DB_STORAGE_TYPE}
    restart: unless-stopped

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100 #Mandatory for Synology NAS
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - ${UPLOAD_LOCATION}:/data:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100 #Mandatory for Synology NAS
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/data:rw
      - ${CACHE_LOCATION}:/cache:rw
      - ${CACHE_LOCATION}:/.cache:rw
      - ${CACHE_LOCATION}:/.config:rw
      - ${MATPLOTLIB_LOCATION}:/matplotlib:rw
    environment:
      MPLCONFIGDIR: /matplotlib
    restart: unless-stopped
    depends_on:
      immich-db:
        condition: service_started
   # Other services...
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:${POWERTOOLS_VERSION:-latest}
    ports:
      - 8001:3000
    environment:
      DB_PORT: ${DB_PORT} #default port for immich db image
      DB_HOST: ${DB_HOST} #hostname, should be the same value as the immich env DB_HOSTNAME
      DB_HOSTNAME: ${DB_HOSTNAME} #immich DB hostname
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      IMMICH_API_KEY: ${IMMICH_API_KEY}
      IMMICH_URL: ${IMMICH_URL}
      EXTERNAL_IMMICH_URL: ${EXTERNAL_IMMICH_URL} #only used for immich apps exposed externally to the internet
